In [ ]:
import numpy as np

def gram_schmidt(vectors):
  A = np.array(vectors, dtype=float).T
  n, k = A.shape
  
  Q = np.zeros((n, k))
  
  for i in range(k):
    a_i = A[:, i]
    q_tilde = a_i
    
    for j in range(i):
      q_j = Q[:, j]
      projection = np.dot(q_j.T, a_i) * q_j
      q_tilde = q_tilde - projection

    norm_q_tilde = np.linalg.norm(q_tilde)
    
    if norm_q_tilde < 1e-10:
      print("linear dependent")
      return Q[:, :i]
    
    Q[:, i] = q_tilde / norm_q_tilde

  return Q

a1 = [1, 1, 0]
a2 = [2, 0, 1]
a3 = [0, 1, 2]
vectors_independent = [a1, a2, a3]

orthonormal_vectors = gram_schmidt(vectors_independent)
print(orthonormal_vectors.T)
print(np.dot(orthonormal_vectors.T, orthonormal_vectors))

print('='*30)

b1 = [1, 0, 1]
b2 = [0, 1, 1]
b3 = [2, 1, 3]
vectors_dependent = [b1, b2, b3]

orthonormal_vectors_dep = gram_schmidt(vectors_dependent)

print(orthonormal_vectors_dep.T)

[[ 0.70710678  0.70710678  0.        ]
 [ 0.57735027 -0.57735027  0.57735027]
 [-0.40824829  0.40824829  0.81649658]]
[[ 1.00000000e+00  2.50235355e-16  1.47380436e-17]
 [ 2.50235355e-16  1.00000000e+00 -3.33168241e-17]
 [ 1.47380436e-17 -3.33168241e-17  1.00000000e+00]]
[[ 0.70710678  0.          0.70710678]
 [-0.40824829  0.81649658  0.40824829]
 [ 0.57735027  0.57735027 -0.57735027]]
